#!/usr/bin/env python3

import os
import subprocess

##hostname
hostname = os.uname().nodename
##user
user = os.getenv("USER")
##uptime
uptime = subprocess.run(["uptime", "-p"], capture_output=True, text=True).stdout.strip()
##disk usage
disk = subprocess.run(["df", "-h", "/"], capture_output=True, text=True).stdout.split("\n")[1].split()
disk_used = disk[4]
##memory usage
mem = subprocess.run(["free", "-h"], capture_output=True, text=True).stdout.split("\n")[1].split()
mem_used = mem[2]
mem_total = mem[1]

print("=== system-info ===")
print(f"Hostname: {hostname}")
print(f"Current User: {user}")
print(f"Uptime: {uptime}")
print(f"Disk Usage: {disk_used}")
print(f"Memory: {mem_used} / {mem_total}")
