#!/usr/bin/env python3

import subprocess

cmd = 'sudo grep "$(date +"%b %e")" /var/log/messages | grep -i error | wc -l'
print("=== log-checker ===")
ERR_COUNT = subprocess.run([cmd], capture_output=True, text=True, shell=True).stdout.strip()

if int(ERR_COUNT) > 0:
    print(f"Error count: {ERR_COUNT}")
else:
    print("no errors today")
