#!/usr/bin/env bash


echo "--  system info  --"
echo "===================="
echo "Hostname: $HOSTNAME"
echo "Current User: $(whoami)"
echo "Up-time: $(uptime -p)"
echo "RAM: $(free -h | awk 'NR==2 {print $2}')"
echo "Disk: $(df -h | grep -i /dev/mapper/rhel-root | awk '{print $2}')"
echo "CPU: $(lscpu | grep -i "model name" | awk -F: '{gsub(/^[ \t]+/, "", $2); print $2}')"
