#!/usr/bin/env bash

read -p "Enter services to check: " -a SERVICES

echo "==== service checker ===="

for SERVICE in "${SERVICES[@]}"; do
	if systemctl is-active --quiet $SERVICE; then
	       echo "$SERVICE is running"
       else
		echo "$SERVICE is STOPPED"
	fi
done	

